language: python

branches:
  only:
  - master

matrix:
  include:
    - python: 3.7
      dist: zenial

install:
  - pip install -r requirements.txt

script:
  - flake8
  - isort -c

after_script:
  - codecov --token=CODECOV_TOKEN